=== hfmarino/graniteds-extension/classes/core/org/granite/config/granite-config.dtd
<!--
  GRANITE DATA SERVICES
  Copyright (C) 2007-2010 ADEQUATE SYSTEMS SARL

  This file is part of Granite Data Services.

  Granite Data Services is free software; you can redistribute it and/or modify
  it under the terms of the GNU Library General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at your
  option) any later version.

  Granite Data Services is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License
  for more details.

  You should have received a copy of the GNU Library General Public License
  along with this library; if not, see <http://www.gnu.org/licenses/>.
-->

<!ELEMENT granite-config (
    amf3-serializer?,
    amf3-deserializer?,
    amf3-message-interceptor?,
    converters?,
    method-matcher?,
    invocation-listener?,
    instantiators?,
    class-getter?,
    externalizers?,
    descriptors?,
    exception-converters?,
    security?,
    tide-components?,
    message-selector?,
    gravity?
)>
<!ATTLIST granite-config
	scan (true|false) "false"
>

<!ELEMENT amf3-serializer EMPTY>
<!ATTLIST amf3-serializer
	type CDATA #REQUIRED
>

<!ELEMENT amf3-deserializer EMPTY>
<!ATTLIST amf3-deserializer
	type CDATA #REQUIRED
>

<!ELEMENT amf3-message-interceptor EMPTY>
<!ATTLIST amf3-message-interceptor
	type CDATA #REQUIRED
>

<!ELEMENT converters (
	converter*
)>
<!ATTLIST converters
	override (true|false) "false"
>
<!ELEMENT converter EMPTY>
<!ATTLIST converter
	type CDATA #REQUIRED
>

<!ELEMENT method-matcher EMPTY>
<!ATTLIST method-matcher
	type CDATA #REQUIRED
>

<!ELEMENT invocation-listener EMPTY>
<!ATTLIST invocation-listener
	type CDATA #REQUIRED
>

<!ELEMENT instantiators (
	instantiator*
)>
<!ELEMENT instantiator (#PCDATA)>
<!ATTLIST instantiator
	type CDATA #REQUIRED
>

<!ELEMENT class-getter EMPTY>
<!ATTLIST class-getter
	type CDATA #REQUIRED
>

<!ELEMENT externalizers (
	configuration?,
	externalizer*
)>
<!ELEMENT configuration ANY>
<!ELEMENT externalizer (
	include+
)>
<!ATTLIST externalizer
	type CDATA #REQUIRED
>
<!ELEMENT include EMPTY>
<!ATTLIST include
	type CDATA #IMPLIED
	instance-of CDATA #IMPLIED
	annotated-with CDATA #IMPLIED
>

<!ELEMENT descriptors (
	descriptor*
)>
<!ELEMENT descriptor EMPTY>
<!ATTLIST descriptor
	type CDATA #IMPLIED
	instance-of CDATA #IMPLIED
	java CDATA #IMPLIED
	as3 CDATA #IMPLIED
>

<!ELEMENT exception-converters (
	exception-converter*
)>
<!ELEMENT exception-converter EMPTY>
<!ATTLIST exception-converter
	type CDATA #REQUIRED
>

<!ELEMENT security (param*)>
<!ATTLIST security
	type CDATA #REQUIRED
>
<!ELEMENT param EMPTY>
<!ATTLIST param
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT tide-components (
	tide-component+
)>
<!ELEMENT tide-component EMPTY>
<!ATTLIST tide-component
	type CDATA #IMPLIED
	name CDATA #IMPLIED
	instance-of CDATA #IMPLIED
	annotated-with CDATA #IMPLIED
	disabled (true|false) "false"
>

<!ELEMENT message-selector EMPTY>
<!ATTLIST message-selector
	type CDATA #REQUIRED
>

<!ELEMENT gravity (
	configuration?,
	thread-pool?
)>
<!ATTLIST gravity
    factory CDATA "org.granite.gravity.DefaultGravityFactory"
    channel-idle-timeout-millis CDATA "1800000"
    long-polling-timeout-millis CDATA "20000"
    retry-on-error (true|false) "true"
    max-messages-queued-per-channel CDATA "2147483647"
    reconnect-interval-millis CDATA "30000"
    reconnect-max-attempts CDATA "60"
>
<!ELEMENT thread-pool EMPTY>
<!ATTLIST thread-pool
    core-pool-size CDATA "5"
    maximum-pool-size CDATA "20"
    keep-alive-time-millis CDATA "10000"
    queue-capacity CDATA "2147483647"
>
<!ELEMENT hibernate-collection-metadata (#PCDATA)>
<!ELEMENT dynamic-class (#PCDATA)>
<!ELEMENT gae EMPTY>
<!ATTLIST gae
    polling-interval CDATA "500"
>

=== hfmarino/graniteds-extension/core/org/granite/config/granite-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE granite-config PUBLIC "-//Granite Data Services//DTD granite-config internal//EN"
    "http://www.graniteds.org/public/dtd/2.0.0/granite-config.dtd">

<!--
  GRANITE DATA SERVICES
  Copyright (C) 2007-2010 ADEQUATE SYSTEMS SARL

  This file is part of Granite Data Services.

  Granite Data Services is free software; you can redistribute it and/or modify
  it under the terms of the GNU Library General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at your
  option) any later version.

  Granite Data Services is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License
  for more details.

  You should have received a copy of the GNU Library General Public License
  along with this library; if not, see <http://www.gnu.org/licenses/>.
-->

<!--
 ! @author Franck WOLFF
 !-->
<granite-config>

    <!--
     ! Standard GDS converters.
     !-->
    <converters>
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2Integer" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2Long" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2Double" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Boolean2Boolean" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Collection2Collection" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Collection2Array" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Array2Array" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Array2Collection" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Date2Date" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Map2Map" />
        <converter type="org.granite.messaging.amf.io.convert.impl.String2CharArray" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2BigDecimal" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2BigInteger" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2Byte" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2Float" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Number2Short" />
        <converter type="org.granite.messaging.amf.io.convert.impl.String2Char" />
        <converter type="org.granite.messaging.amf.io.convert.impl.String2Locale" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Character2Character" />
        <converter type="org.granite.messaging.amf.io.convert.impl.Compatibility" />
        <converter type="org.granite.messaging.amf.io.convert.impl.String2Document" />
    </converters>
    
    <externalizers>
    	<externalizer type="org.granite.messaging.amf.io.util.externalizer.EnumExternalizer">
    		<include instance-of="java.lang.Enum"/>
    	</externalizer>
    	<externalizer type="org.granite.messaging.amf.io.util.externalizer.MathContextExternalizer">
    		<include instance-of="java.math.MathContext"/>
    	</externalizer>
    	<!--
    	<externalizer type="org.granite.messaging.amf.io.util.externalizer.LongExternalizer">
    		<include instance-of="java.lang.Long"/>
    	</externalizer>
    	<externalizer type="org.granite.messaging.amf.io.util.externalizer.BigIntegerExternalizer">
    		<include instance-of="java.math.BigInteger"/>
    	</externalizer>
    	<externalizer type="org.granite.messaging.amf.io.util.externalizer.BigDecimalExternalizer">
    		<include instance-of="java.math.BigDecimal"/>
    	</externalizer>
    	-->
    </externalizers>

</granite-config>

=== hfmarino/graniteds-extension/test/graniteds_test/resources/WEB-INF/granite/granite-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE granite-config PUBLIC "-//Granite Data Services//DTD granite-config internal//EN"
    "http://www.graniteds.org/public/dtd/2.0.0/granite-config.dtd">

<!--
  GRANITE DATA SERVICES
  Copyright (C) 2007-2010 ADEQUATE SYSTEMS SARL

  This file is part of Granite Data Services.

  Granite Data Services is free software; you can redistribute it and/or modify
  it under the terms of the GNU Library General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at your
  option) any later version.

  Granite Data Services is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License
  for more details.

  You should have received a copy of the GNU Library General Public License
  along with this library; if not, see <http://www.gnu.org/licenses/>.
-->

<granite-config scan="true">

	<class-getter type="org.granite.tide.test.TestClassGetter"/>
    
   <!--
    ! Use Seam based security service.
    !-->
    <security type="org.granite.seam21.security.Seam21SecurityService"/>
    
    <!--
     ! Enable Seam components for Tide
     !-->
    <tide-components>
        <tide-component instance-of="org.jboss.seam.security.Identity"/>
        <tide-component instance-of="org.jboss.seam.framework.Home"/>
        <tide-component instance-of="org.jboss.seam.framework.Query"/>
        <tide-component type="org\.granite\.tide\.test\..*"/>
    </tide-components>

</granite-config>
